/*
 * Copyright (c) 2012 Bucknell University
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: L. Felipe Perrone (perrone@bucknell.edu)
 */

/*
 * This is a skeleton program for analyzing Ethernet packet traces
 * generated by 'wireshark', or 'tcpdump.'
 *
 * Revised by Xiannong Meng for CSCI 363 Spring 2013
 * By copying the pcap header structures here, we don't have to include
 * pcap.h file here.
 */

#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/socket.h>
#include <net/if.h>
#include <netinet/in.h>
#include <netinet/if_ether.h>
#include <arpa/inet.h>
#include <time.h>

#define int32 int
#define int16 short

#define uint32 unsigned int
#define uint16 unsigned short

#define MAX_ETH_FRAME_LEN 2000  // maximum Ethernet frame length

/* The following structure is the same as defined in pcap.h */
struct pcap_hdr_s { // Global header for libpcap file
  uint32 magic_number;   /* magic number */
  uint16 version_major;  /* major version number */
  uint16 version_minor;  /* minor version number */
  int32  thiszone;       /* GMT to local correction */
  uint32 sigfigs;        /* accuracy of timestamps */
  uint32 snaplen;        /* max length of captured packets, in octets */
  uint32 network;        /* data link type */
};

/* The following structure is the same as defined in pcap.h */
/*
 * For each Ethernet frame recorded in the trace file you are given,
 * there exists a corresponding header created during the capture of
 * the frame. To be more accurate, the trace file you are given does
 * not contain an entire Ethernet frame, only its header. This file is
 * formatted as a collection of tuples <rechdr, ethhdr>. 
 *
 */
struct pcaprec_hdr_s { // Record (packet) header
  uint32         tv_sec;
  uint32         tv_usec; /* time when packet was captured */
  uint32         caplen;	/* length of portion captured */
  uint32         len;	        /* length of original packet (off wire) */
};

/*
 * The main function is mostly a skeleton with a few steps
 * provided. Students need to understand what each step is
 * doing before implementing them.
 */
int main(int argc, char* argv[]){

  struct pcap_hdr_s file_header;
  struct pcaprec_hdr_s frame_header;
  int size_read;
  char * buf;

  // use input redict, etherTrace < data-file, to read file header first
  read(0, &file_header, sizeof(struct pcap_hdr_s));
  buf = (char*)malloc(file_header.snaplen); // maximum length in bytes

  // read the next frame header, referring to the format defined in
  // struct pcaprec_hdr_s
  size_read = read(0, &frame_header, sizeof(struct pcaprec_hdr_s));

  while (size_read > 0) {
    // extract the time stamp
    long time_val = frame_header.tv_sec;
    printf("time captured %ld %s\n", time_val, ctime((const time_t *)&(time_val)));
    
    // read the frame content into 'buf'
    size_read = read(0, buf, frame_header.caplen); 

    /*
     *     extract Ethernet addresses, IP addresses and protocol type
     *     print information extracted
     *
     *
     */
    
    // advance to the next packet header
    size_read = read(0, &frame_header, sizeof(struct pcaprec_hdr_s));

  }  // end of while
  
  /* close trace data file */

  return 0;
}
